name: send-news

on:
  schedule:
    - cron: '0 1 * * *'  # 每天台灣早上 9 點
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 python-telegram-bot

    - name: Run script
      run: python send_news.py
